// Package init intercepts DNS queries generated by the default net Resolver.
//
// To automatically enable, link this package into your program:
//	import _ "github.com/jjeffcaii/dns/init"
//
package init

import (
	"net"

	"github.com/jjeffcaii/dns"
)

func init() {
	net.DefaultResolver = &net.Resolver{
		PreferGo: true,

		Dial: (&dns.Client{
			Resolver: new(dns.Cache),
		}).Dial,
	}
}
